# Generated by Django 2.1.2 on 2018-10-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_auto_20181026_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('density', models.FloatField()),
            ],
        ),
    ]
